name: E2E Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  e2e-test:
    runs-on: macos-latest
    defaults:
      run:
        # https://github.com/actions/runner-images/issues/264#issuecomment-574032011
        shell: zsh -e {0}
    steps:
      - name: Set Xcode CommandLineTools path
        run: sudo xcode-select -s /Library/Developer/CommandLineTools
      - name: Uninstall CommandLineTools ( 1 minutes )
        run: sudo rm -rf /Library/Developer/CommandLineTools
      - name: Uninstall Homebrew ( 4 minutes )
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
      - name: Run test
        run: sudo curl https://raw.githubusercontent.com/blendthink/dotfiles/main/install.zsh | zsh
